{
 "title": "Étape",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "etapes",
    "label": "Étape : ",
    "query": "SELECT numeroEtape \nFROM etape\n"
   },
   {
    "name": "type",
    "label": "type",
    "query": "SELECT type.type\nFROM type\nJOIN etape\nON type.idT = etape.idType\nWHERE etape.numeroEtape = '$etapes'"
   },
   {
    "name": "villeD",
    "query": "SELECT nomV FROM ville \nJOIN etape on etape.idVilleDepart = ville.idV \nWHERE numeroEtape = ${etapes}"
   },
   {
    "name": "villeA",
    "query": "SELECT nomV FROM ville \nJOIN etape on etape.idVilleArrivee = ville.idV \nWHERE numeroEtape = ${etapes}"
   },
   {
    "name": "date",
    "query": "SELECT DATE_FORMAT(date, '%d/%m/%Y') FROM etape\nWHERE numeroEtape = '$etapes'"
   },
   {
    "name": "distance",
    "query": "SELECT distance FROM etape\nWHERE numeroEtape = '$etapes'"
   },
   {
    "name": "url",
    "query": "SELECT urlPhotoEt FROM etape\nWHERE numeroEtape = '$etapes'"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "# Étape ${etapes}\n---\n## Date : ${date}\n## Ville de Départ : ${villeD}\n## Ville d'Arrivée : ${villeA}\n---\n## Type d'étape : ${type}\n---\n<img src=\"https://cdn.xsolla.net/merchant-bucket-prod/files/uploaded/sitebuilder/68486/9213790f13f905ebf374bb6564d6b530.png\" alt=\"image\" width=\"150\" height=\"auto\">"
   },
   "targets": [
    { "dataset": "NOM_BDD" }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 12, "w": 9, "x": 7, "y": 0 },
   "targets": [
    {
     "dataset": "NOM_BDD",
     "rawSql": "SELECT nomV as Ville, latitude, longitude\r\nFROM ville\r\nWHERE nomV = '$villeA' \r\nOR nomV = '$villeD'"
    }
   ]
  },
  {
   "title": "Distance de l'Étape",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NOM_BDD",
     "rawSql": "SELECT distance FROM etape WHERE ${etapes} = numeroEtape"
    }
   ]
  },
  {
   "title": "Dénivelé de L'Étape",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NOM_BDD",
     "rawSql": "SELECT denivele FROM etape WHERE numeroEtape = '$etapes'"
    }
   ]
  },
  {
   "title": "Vitesse Moyenne de l'Étape",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NOM_BDD",
     "rawSql": "SELECT numeroEtape, vitesseMoyenne FROM view_etape_vitesse WHERE ${etapes} = numeroEtape"
    }
   ]
  },
  {
   "title": "Nombre de Cols",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "NOM_BDD",
     "rawSql": "SELECT nbCol4 as '4ème Catégorie', nbCol3 as '3ème Catégorie', nbCol2 as '2ème Catégorie', nbCol1 as '1ère Catégorie', nbColHC as 'Hors-Catégorie' FROM view_nbcols_etape WHERE ${etapes} = numeroEtape"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 12 },
   "options": {
    "content": "<table>\r\n  <tr>\r\n    <td><img src=\"${url}\" alt=\"image\" height=\"300\" width=\"auto\"><td>\r\n    <td><h3 style=\"text-align: center\">Profil d'étape fourni par ASO</h3><br><br><img src=\"https://www.aso.fr/img/dyn/event/1@2x.png\"></td>\r\n  </tr>\r\n</table>\r\n"
   },
   "targets": [
    { "dataset": "NOM_BDD" }
   ]
  }
 ]
}