{
 "title": "Global",
 "time": { "from": "2023-06-30T22:00:00.000Z", "to": "2023-07-23T22:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "type", "label": "type", "query": "SELECT type.type\nFROM type" },
   {
    "name": "dateDebut",
    "query": "SELECT DATE_FORMAT(date, '%d %M %Y')\nFROM etape\nWHERE etape.numeroEtape = 1;"
   },
   {
    "name": "dateFin",
    "query": "SELECT DATE_FORMAT(date, '%d %M %Y')\nFROM etape\nWHERE etape.numeroEtape = 21;"
   },
   {
    "name": "distanceTotale",
    "query": "SELECT SUM(distance)\nFROM etape"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Tour de France 2023\n---\n## - du ${dateDebut} au ${dateFin}\n## - 176 coureurs\n## - 21 étapes, ${distanceTotale} km au total\n---\n<img src=\"https://cdn.xsolla.net/merchant-bucket-prod/files/uploaded/sitebuilder/68486/9213790f13f905ebf374bb6564d6b530.png\" alt=\"image\" width=\"150\" height=\"auto\">"
   },
   "targets": [
    { "dataset": "aastier" }
   ]
  },
  {
   "title": "Liste des Étapes",
   "type": "table",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "fcastella",
     "rawSql": "SELECT numEtape as 'Numéro d''Étape', dates as 'Date', villeD as 'Ville de Départ', villeA as 'Ville d''Arrivée', type as 'Type'\r\nFROM ANALYSE_ETAPE_BASE"
    }
   ]
  },
  {
   "title": "Villes accueillant les Étapes",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dataset": "aastier",
     "rawSql": "SELECT nomV, latitude, longitude\r\nFROM ville"
    }
   ]
  },
  {
   "title": "Nombre d'Étapes par Types",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aastier",
     "rawSql": "SELECT type, nombreEtape\r\nFROM ANALYSE_ETAPE_NBTYPE"
    }
   ]
  },
  {
   "title": "Répartition des Cols sur chaque Étape",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "dataset": "aastier",
     "rawSql": "SELECT date, nbCol4, nbCol3, nbCol2, nbCol1, nbColHC\r\nFROM etape"
    }
   ]
  },
  {
   "title": "Nombre de cols de chaque catégorie ",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aastier",
     "rawSql": "SELECT SUM(nbcol1) AS '1ère Catégorie'\r\n,SUM(nbcol2) AS '2ème Catégorie',\r\nSUM(nbcol3) AS '3ème Catégorie',\r\nSUM(nbcol4)AS '4ème Catégorie',\r\nSUM(nbcolHC) AS 'Hors-Catégorie'\r\nFROM etape "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 33 },
   "options": {
    "content": "<br>\r\n<h1 style=\"text-align: center; font-size:50px\">Informations par Type</h1>"
   },
   "targets": [
    { "dataset": "aastier" }
   ]
  },
  {
   "title": "Liste des Étapes",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "dataset": "fcastella",
     "rawSql": "SELECT numEtape as 'Numéro d''Étape', dates as 'Date', villeD as 'Ville de Départ', villeA as 'Ville d''Arrivée', type as 'Type'\r\nFROM ANALYSE_ETAPE_BASE\r\nWHERE type = '$type' "
    }
   ]
  },
  {
   "title": "Nombre d'étapes ($type)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aastier",
     "rawSql": "SELECT COUNT(*)\r\nFROM etape\r\nJOIN type\r\nON etape.idType = type.idT\r\nWHERE type.type = '$type'"
    }
   ]
  },
  {
   "title": "Villes accueillant ces Étapes",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "dataset": "aastier",
     "rawSql": "SELECT nomV, latitude, longitude\r\nFROM ville\r\nJOIN etape\r\nON etape.idVilleDepart = ville.idV OR etape.idVilleArrivee = ville.idV\r\nJOIN type\r\nON etape.idType = type.idT\r\nWHERE type.type = '$type'"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 47 },
   "options": {
    "content": "<br>\r\n<h1 style=\"text-align: center; font-size:50px\">Informations sur les Coureurs</h1>"
   },
   "targets": [
    { "dataset": "aastier" }
   ]
  },
  {
   "title": "Coureurs ayant fini le Tour",
   "type": "table",
   "gridPos": { "h": 33, "w": 4, "x": 0, "y": 50 },
   "targets": [
    {
     "dataset": "fcastella",
     "rawSql": "SELECT nomC as Nom\r\nFROM coureur\r\nJOIN coureurs_ayants_fini\r\nON coureur.idC = coureurs_ayants_fini.idC\r\nORDER BY nomC"
    }
   ]
  },
  {
   "title": "Coureurs n'ayant pas fini le Tour",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 50 },
   "targets": [
    {
     "dataset": "fcastella",
     "rawSql": "SELECT nomC as Nom\r\nFROM coureurs_ayants_pas_fini"
    }
   ]
  },
  {
   "title": "Nombre de coureurs dans les équipe en ayant 3 ou plus",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "aastier",
     "rawSql": "SELECT nomE, COUNT(*) as Coureurs\r\nFROM coureur\r\nJOIN equipe\r\nON coureur.idEquipe = equipe.idE\r\nGROUP BY nomE\r\nHAVING COUNT(*) >= 3;"
    }
   ]
  },
  {
   "title": "Coureurs dont le prénom commence par J",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 57 },
   "targets": [
    {
     "dataset": "aastier",
     "rawSql": "SELECT nomC as Nom\r\nFROM coureur\r\nWHERE nomC REGEXP('^J');\r\n"
    }
   ]
  },
  {
   "title": "Coureurs ayants fini au moins une fois 1er",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "dataset": "aastier",
     "rawSql": "SELECT nomC as Nom, MIN(classementEtape)\r\nFROM coureur\r\nJOIN classement\r\nON coureur.idC = classement.idC\r\nGROUP BY nomC\r\nHAVING MIN(classementEtape) = 1"
    }
   ]
  },
  {
   "title": "Coureurs ayant un nom de 5 lettres",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 4, "y": 64 },
   "targets": [
    {
     "dataset": "aastier",
     "rawSql": "SELECT nomC as Nom\r\nFROM coureur\r\nWHERE SUBSTRING(nomC FROM 4) REGEXP('^.{5}$');"
    }
   ]
  }
 ]
}